name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest

    name: "macOS (Xcode ${{ matrix.xcode }})"

    strategy:
      matrix:
        xcode: ["12.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  linux:
    runs-on: ubuntu-latest

    name: "Linux (Swift ${{ matrix.swift }})"

    strategy:
      matrix:
        swift: ["5.3"]

    container:
      image: swift:${{ matrix.swift }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: swift test --enable-test-discovery
